# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62410a6a21fad169f852c01df84570fd5092d2027b00b3e5806367f50707f146baffff418f5735e24c5dfa39fd61a34dd222cc563607b9128fb2ee4f44fd7630

test:
  secret_key_base: 79b2242e575841d45e49a454f7f278d0fbdab5ba0bdd0f57c347485ad8808cc1286fec03ec5999bf3aafb88fdd7468915ba70290303d0309ad594fa2b44e82f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
